os: linux
language: python

branches:
  only:
    - master
    - travis

jobs:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=docs

    - python: 3.6
      env: TOXENV=py36-django2.2-drf3.10
    - python: 3.6
      env: TOXENV=py36-django2.2-drf3.11
    - python: 3.6
      env: TOXENV=py36-django3.0-drf3.10
    - python: 3.6
      env: TOXENV=py36-django3.0-drf3.11
    - python: 3.6
      env: TOXENV=py36-djmaster

    - python: 3.7
      env: TOXENV=py37-django2.2-drf3.10
    - python: 3.7
      env: TOXENV=py37-django2.2-drf3.11
    - python: 3.7
      env: TOXENV=py37-django3.0-drf3.10
    - python: 3.7
      env: TOXENV=py37-django3.0-drf3.11
    - python: 3.7
      env: TOXENV=py37-djmaster

    - python: 3.8
      env: TOXENV=py38-django2.2-drf3.10
    - python: 3.8
      env: TOXENV=py38-django2.2-drf3.11
    - python: 3.8
      env: TOXENV=py38-django3.0-drf3.10
    - python: 3.8
      env: TOXENV=py38-django3.0-drf3.11
    - python: 3.8
      env: TOXENV=py38-djmaster

  allow_failures:
    - env: TOXENV=py36-djmaster
    - env: TOXENV=py37-djmaster
    - env: TOXENV=py38-djmaster

install:
  - pip install -U pip
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV
