os: linux
language: python

branches:
  only:
    - master
    - travis

jobs:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=docs

    - python: 3.6
      env: TOXENV=py36-django2.2-drf3.10
    - python: 3.6
      env: TOXENV=py36-django2.2-drf3.11
    - python: 3.6
      env: TOXENV=py36-django3.0-drf3.10
    - python: 3.6
      env: TOXENV=py36-django3.0-drf3.11

    - python: 3.7
      env: TOXENV=py37-django2.2-drf3.10
    - python: 3.7
      env: TOXENV=py37-django2.2-drf3.11
    - python: 3.7
      env: TOXENV=py37-django3.0-drf3.10
    - python: 3.7
      env: TOXENV=py37-django3.0-drf3.11
    - python: 3.7
      env: TOXENV=py37-django3.0-drf3.12
    - python: 3.7
      env: TOXENV=py37-django3.1-drf3.11
    - python: 3.7
      env: TOXENV=py37-django3.1-drf3.12

    - python: 3.8
      env: TOXENV=py38-django2.2-drf3.10
    - python: 3.8
      env: TOXENV=py38-django2.2-drf3.11
    - python: 3.8
      env: TOXENV=py38-django3.0-drf3.10
    - python: 3.8
      env: TOXENV=py38-django3.0-drf3.11
    - python: 3.8
      env: TOXENV=py38-django3.0-drf3.12
    - python: 3.8
      env: TOXENV=py38-django3.1-drf3.11
    - python: 3.8
      env: TOXENV=py38-django3.1-drf3.12

    - python: 3.9
      env: TOXENV=py39-django3.1-drf3.11
    - python: 3.9
      env: TOXENV=py39-django3.1-drf3.12

    - python: 3.8
      env: TOXENV=py38-django3.1-drfmaster
    - python: 3.8
      env: TOXENV=py38-djangomaster-drf3.12
    - python: 3.8
      env: TOXENV=py38-drfmaster-djangomaster
    - python: 3.8
      env: TOXENV=py38-drfmaster-djangomaster-allowcontribfail

  allow_failures:
    - env: TOXENV=py38-django3.1-drfmaster
    - env: TOXENV=py38-djangomaster-drf3.12
    - env: TOXENV=py38-drfmaster-djangomaster
    - env: TOXENV=py38-drfmaster-djangomaster-allowcontribfail

install:
  - pip install -U pip
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV
